[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#0f1115"
secondaryBackgroundColor = "#181b21"
textColor = "#e8eaea"
font = "sans-serif"
baseFontSize = 17
headingFontSizes = ["34px", "27px", "22px", "19px", "17px", "16px"]
headingFontWeights = [700, 700, 600, 600, 600, 600]
baseRadius = "8px"

[server]
headless = true
